### PR TITLE
V2.3.0

### PR DESCRIPTION
**Pull request by mcflugen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mcflugen** [comment]
@hobu Thanks so much for helping out with this! I was planning on working on the Windows builds today but it looks like you already have a handle on that.

**Comment by mcflugen** [comment]
@hobu It looks like you're on a roll so I don't want to get in the way and slow your momentum. In case it helps, though, I was going to try the following *bld.bat* file,
```powershell
mkdir build && cd build

cmake -LAH -G "NMake Makefiles" ^
  -DCMAKE_INSTALL_PREFIX:PATH=%LIBRARY_PREFIX% ^
  -DCMAKE_PREFIX_PATH:PATH="%LIBRARY_PREFIX%" ^
  -DCMAKE_BUILD_TYPE=Release ^
  %SRC_DIR%
if errorlevel 1 exit 1

cmake --build . --target install --config Release
if errorlevel 1 exit 1

python -m pip install wrappers\pyrichdem --no-deps -vv
```
I don't have access to a Windows machine at the moment so I can't test this, unfortunately.

**Comment by hobu** [comment]
Looks like we need a patch to add `<numeric>` somewhere for windows

**Comment by mcflugen** [comment]
These latest errors look to be a little trickier. I may have to track down a Windows machine.

**Comment by hobu** [comment]
Thanks for all the hard work!

**Pull request merged**
